# Generated by Django 6.0.3 on 2026-03-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_refund_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment'),
        ),
    ]
