# Generated by Django 6.0.3 on 2026-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_useranalytics_total_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractanalytics',
            name='total_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
