# Generated by Django 6.0.3 on 2026-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Acceptance'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
