# Generated by Django 6.0.3 on 2026-03-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_milestonestatus_milestonesubmission_milestonereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestonestatus',
            old_name='old_status',
            new_name='prev_status',
        ),
    ]
