# Generated by Django 6.0.3 on 2026-03-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_rename_old_status_milestonestatus_prev_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
