# Generated by Django 6.0.3 on 2026-03-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_milestone_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
