# Generated by Django 6.0.3 on 2026-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0005_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
